version: '3'
services: 
  web:
    #env vairbale below lets updating happen in real time only for react apps
    environment: 
      #https://stackoverflow.com/questions/44643045/running-development-server-with-create-react-app-inside-of-a-docker-container
      - CHOKIDAR_USEPOLLING=true
    build: 
      #context -> where we want all the files and folders for this image to be pulled from
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app
  tests:
    environment: 
      - CHOKIDAR_USEPOLLING=true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
    